### ISSUE TITLE
Support mini breakout board or SparkFun Edison boards?

### ISSUE THREAD

**Issue by gfguthrie** [hybridgroup/cylon-intel-iot#12]
Not sure what would exactly be involved in adding support, but it would be a nice feature given how much smaller these boards are & the kinds of applications they are better suited for. Or do they work unofficially?

**Comment by deadprogram** [comment]
Hi, @gfguthrie the mini breakout board should work right now. The Sparkfun boards are a different story, more on that soon...

**Comment by ben-rowe** [comment]
I have a similar issue, I found that the i2c pin is hardcoded to be 6 where as the sparkfun 9DOF board uses pin 1 i just switched it as i'm not using the device for anything else. I'm getting data all be it with some rather crazy values.
Modify file: 
https://github.com/hybridgroup/cylon-intel-iot/blob/master/lib/utils.js
on line 19: return 6
should be: return 1

**Comment by deadprogram** [comment]
Hi, @ben-rowe I just added the branch https://github.com/hybridgroup/cylon-intel-iot/tree/feature/specify-i2c-port that allows you to specify which i2c port to use like this:

```
connections: {
    edison: { adaptor: "intel-iot", i2cPort: 1 }
  },
```

Can you try this and see if it works for you? Thanks!

**Comment by edgarsilva** [comment]
@gfguthrie any luck with this? @deadprogram seems like this branch has been merged and released already. Should we close?

**Comment by deadprogram** [comment]
@gfguthrie and/or @ben-rowe we've merged and released this feature. Can you please verify so we can close? Thanks!

**Comment by deadprogram** [comment]
Hi, @gfguthrie and/or @ben-rowe can you verify to see if this is working for you? It is for me with my Sparkfun board.

**Comment by deadprogram** [comment]
This was resolved quite a while ago, please reopen if needed. Thanks, everyone.
