### ISSUE TITLE
Not possible to programmatically pair with bluetooth device?

### ISSUE THREAD

**Issue by rclai** [hybridgroup/cylon-intel-iot#18]
In this guide: http://cylonjs.com/documentation/platforms/edison/

When it talks about the Bluetooth pairing, is it not possible to programmatically pair with a device instead of having to use `bluetoothctl`?

**Comment by deadprogram** [comment]
Hi @rclai 

We have a command line tool called Gort (http://gort.io/) which can do this. It is currently being updated for BlueZ 5.x in the `dev` branch: https://github.com/hybridgroup/gort

I hope to have the new release completed by next week.

**Comment by rclai** [comment]
Oh cool thanks.
