### ISSUE TITLE
Adafruit Motorshield v2

### ISSUE THREAD

**Issue by ashishdatta** [hybridgroup/cylon-intel-iot#6]
Hi, I would like to use an Adafruit motorshield to drive a nodebot I am building. Does cylon have support for it? https://learn.adafruit.com/adafruit-motor-shield-v2-for-arduino/overview

Thanks

**Comment by edgarsilva** [comment]
Any updates on this? it's been a while with no follow up, I'm closing the issue. We can reopen in the correct https://github.com/hybridgroup/cylon-i2c/issues module when we implement it.
